version: '3.4'

services:
  api:
    image: trainticketmachine-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    networks:
      - default
    ports:
      - "8080:80"

networks:
  default: